version: 2.1

orbs:
  codecov: codecov/codecov@6.0.0

executors:
  node:
    parameters:
      version:
        type: string
        default: lts
    docker:
      - image: cimg/node:<< parameters.version >>
    working_directory: ~/marpit

commands:
  install:
    parameters:
      force:
        type: boolean
        default: false
      postinstall:
        type: steps
        default: []
    steps:
      - restore_cache:
          keys:
            - v3-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}-{{ .Branch }}
            - v3-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}-
            - v3-dependencies-{{ .Environment.CIRCLE_JOB }}-

      - run: npm ci <<# parameters.force >>--force<</ parameters.force >>
      - steps: << parameters.postinstall >>

      - save_cache:
          key: v2.3-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}-{{ .Branch }}
          paths:
            - ~/.npm

  audit:
    steps:
      - checkout:
          method: blobless
      - install:
          postinstall:
            - run: npm -s run check:audit

  prepare:
    parameters:
      force:
        type: boolean
        default: false
    steps:
      - run: node --version

      - checkout:
          method: blobless

      - install:
          force: << parameters.force >>

  lint:
    steps:
      - run:
          name: Prettier formatting
          command: npm run check:format

      - run:
          name: ESLint
          command: npm run lint:js

      - run:
          name: stylelint
          command: npm run lint:css

  test:
    parameters:
      legacy:
        type: boolean
        default: false
      junit:
        type: boolean
        default: true
    steps:
      - run:
          name: Jest
          command: npm run test:coverage -- --ci --maxWorkers=2 --reporters=default <<# parameters.junit >>--reporters=jest-junit<</ parameters.junit >> <<# parameters.legacy >>--config jest.legacy.config.js --coverage=false<</ parameters.legacy >>
          environment:
            JEST_JUNIT_OUTPUT_DIR: tmp/test-results

      - unless:
          condition: << parameters.legacy >>
          steps:
            - codecov/upload
            - store_artifacts:
                path: ./coverage
                destination: coverage

      - when:
          condition: << parameters.junit >>
          steps:
            - store_test_results:
                path: tmp/test-results

jobs:
  audit:
    executor: node
    steps:
      - audit

  build-tests-for-legacy-node:
    executor:
      name: node
      version: '26.8.1' # Specify version for development
    steps:
      - prepare
      - run: npm run build:test
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - tmp/legacy-test

  test-node18:
    executor:
      name: node
      version: '18.20'
    steps:
      - prepare:
          force: true
      - attach_workspace:
          at: .
      - test:
          legacy: true
          junit: false

  test-node20:
    executor:
      name: node
      version: '20.20'
    steps:
      - prepare
      - lint
      - attach_workspace:
          at: .
      - test:
          legacy: true

  test-node22:
    executor:
      name: node
      version: '22.23'
    steps:
      - prepare
      - lint
      - test

  test-node24:
    executor:
      name: node
      version: '24.20'
    steps:
      - prepare
      - lint
      - test

  test-node26:
    executor:
      name: node
      version: '26.8.1' # Specify version for development
    steps:
      - prepare
      - lint
      - test

workflows:
  test:
    jobs:
      - audit

      # For legacy Node.js
      - build-tests-for-legacy-node:
          requires:
            - audit
      - test-node18:
          requires:
            - build-tests-for-legacy-node
      - test-node20:
          requires:
            - build-tests-for-legacy-node

      # For active Node.js
      - test-node22:
          requires:
            - audit
      - test-node24:
          requires:
            - audit
      - test-node26:
          requires:
            - audit
